workflows:
  macos-build:
    name: macOS Build
    instance_type: mac_mini_m2
    max_build_duration: 120

    environment:
      xcode: latest

    cache:
      cache_paths:
        - ~/.cache/pip

    scripts:
      - name: Install dependencies
        script: |
          set -x
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install pyinstaller
      - name: Build the application
        script: |
          set -x
          sh scripts/build_macos.sh

    artifacts:
      - build/macos/*.dmg
